name: posventa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  crypto: ^3.0.7
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
