name: posventa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  animate_do: ^4.2.0
  audioplayers: ^6.0.0
  collection: ^1.19.1
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  image_picker: ^1.0.7
  intl: ^0.20.2
  mobile_scanner: ^7.1.3
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.7.1

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
