name: posventa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  animate_do: ^4.2.0
  audioplayers: ^6.0.0
  barcode_widget: ^2.0.4
  bcrypt: ^1.2.0
  blue_thermal_printer: ^1.2.3
  crypto: ^3.0.7
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  encrypt: ^5.0.3
  equatable: ^2.0.7
  file_picker: ^10.3.8
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_esc_pos_utils: ^1.0.1
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_slidable: ^4.0.3
  fpdart: ^1.2.0
  go_router: ^17.0.0
  google_fonts: ^7.0.2
  image: ^4.5.4
  image_picker: ^1.0.7
  intl: ^0.20.2
  logging: ^1.3.0
  mobile_scanner: ^7.1.3
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  printing: ^5.14.2
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  window_manager: ^0.5.1

dev_dependencies:
  build_runner: ^2.10.4

  drift_dev: ^2.30.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
